# Generated by Django 3.2.9 on 2021-12-13 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityAvailable', models.CharField(max_length=55, verbose_name='City')),
            ],
            options={
                'verbose_name': 'City available',
            },
        ),
        migrations.CreateModel(
            name='SetNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='disattiva')),
            ],
            options={
                'verbose_name': 'Notifiche gestionale',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsKennel', models.BooleanField(verbose_name='Kennel checked')),
                ('city', models.CharField(max_length=55, verbose_name='City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utenti Canili',
            },
        ),
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushat', models.DateField(auto_created=True, auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('city', models.CharField(max_length=55, verbose_name='City')),
                ('address', models.CharField(max_length=55, verbose_name='address')),
                ('cap', models.IntegerField(blank=True, null=True, verbose_name='cap address')),
                ('checked', models.BooleanField(verbose_name='Kennel checked')),
                ('piva', models.CharField(blank=True, max_length=55, null=True, verbose_name='P.IVA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'kennel',
                'verbose_name_plural': 'Kennels',
            },
        ),
    ]
