# Generated by Django 3.1.13 on 2021-12-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushat', models.DateField(auto_created=True, auto_now_add=True)),
                ('sender', models.EmailField(max_length=254, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email inviate',
            },
        ),
    ]
